---
title: "Circuit winner"
output: html_document
---

```{r setup, echo = T, message=F}
require(knitr)
opts_chunk$set(fig.path = "images/ergastdatadb-")
```


# Circuit Winner

How well a driver does at a circuit

```{r}

library(RMySQL)
ergastdb=dbConnect(MySQL(),user='root',password='f1',host='127.0.0.1',port=3399,dbname='ergastdb')
```


```{r results='asis'}
 q='SELECT  * FROM races r JOIN circuits c ON r.circuitId=c.circuitID WHERE circuitref="albert_park"'
 #The dbGetQuery() function is provided by the DBI library
dbGetQuery(ergastdb, q)
```

```{r}
q='SELECT driverRef, code, MAX(year) as until,SUM(11-position) s FROM races r JOIN circuits c JOIN results rs JOIN drivers d WHERE r.circuitId=c.circuitId AND r.raceId=rs.raceId AND position<=10 AND d.driverID=rs.driverId AND circuitref="albert_park" GROUP BY driverRef, code  DESC HAVING s > 50 ORDER BY s'
leaders = dbGetQuery(ergastdb, q)
leaders
```

```{r}
leaders$code

```


```{r results='asis'}
q='SELECT year, driverRef, code, position FROM races r JOIN circuits c JOIN results rs JOIN drivers d WHERE r.circuitId=c.circuitId AND r.raceId=rs.raceId AND position<=10 AND d.driverID=rs.driverId AND circuitref="albert_park" ORDER BY year'
 #The dbGetQuery() function is provided by the DBI library
res = dbGetQuery(ergastdb, q)
res

```

```{r}
res$pts = 11-res$position

res
```

```{r}
library(plyr)
res = ddply(res, .(driverRef), transform, totPts=cumsum(pts)  )
res
```




```{r}
library(ggplot2)
library(directlabels)
library(ggrepel)
library(ggthemes)

g=ggplot(res, aes(x=year, y=totPts))+ geom_step(aes( col=code))
#g=g+geom_label_repel(data=leaders,aes(x=until, y=s,label = driverRef),nudge_x = 1, na.rm = TRUE)
g=g+geom_dl(data=leaders,aes(x=until, y=s,label = code), method = list(dl.combine( "last.points")), cex = 0.8) 
g + guides(color=FALSE)
```


```{r}

g=ggplot(res, aes(x=year, y=totPts))+ geom_step(aes( col=code))
g=g+geom_label_repel(data=leaders,aes(x=until, y=s,label = code),nudge_x = -10,nudge_y = 1, na.rm = TRUE)

g + guides(color=FALSE)
```

```{r}

g=ggplot(res, aes(x=year, y=totPts))+ geom_line(aes( col=code))
g=g+geom_label_repel(data=leaders,aes(x=until, y=s,label = code),nudge_x = -0,nudge_y = 10, na.rm = TRUE, arrow = arrow(length = unit(0.01, 'npc')))

g + guides(color=FALSE)+xlim(1995,2030)+ylim(0,100)
```

```{r}

g=ggplot()+ geom_step(data=res[res$code %in% leaders$code,], aes(x=year, y=totPts, col=code))
g=g+ geom_line(data=res[!(res$code %in% leaders$code),], aes(x=year, y=totPts, group=driverRef),col='grey')
g=g+geom_label_repel(data=leaders,aes(x=until, y=s,label = code), na.rm = TRUE, arrow = arrow(length = unit(0.01, 'npc')), nudge_y =3, nudge_x =2, segment.size = 0.2,size=2)

g=g + guides(color=FALSE)+xlim(1993,2025)+ylim(0,110)+theme_bw()+ggtitle('F1 Australia - Albert Park - Driver Performance')
g=g+annotate("rect", xmin = 1994, xmax = 2006, ymin = 75, ymax = 110,
  alpha = 1, fill='lightblue')
g+ annotate("text", x = 2000, y = 95, label = "10 points for 1st\ndown to 1 point for 10th")+ylab('Total "Points"')+xlab(NULL)
```


```{r}
g=ggplot(res, aes(x=year, y=totPts))+ geom_step(aes( col=code))
g=g+geom_text_repel(data=leaders,aes(x=until, y=s,label =   code),nudge_x = -1,nudge_y = 1, na.rm = TRUE)

g + guides(color=FALSE)
```

